/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AActualGlobalParameterTail extends PActualGlobalParameterTail
{
    private TComma _comma_;
    private PActualGlobalParameter _actualGlobalParameter_;

    public AActualGlobalParameterTail()
    {
    }

    public AActualGlobalParameterTail(
        TComma _comma_,
        PActualGlobalParameter _actualGlobalParameter_)
    {
        setComma(_comma_);

        setActualGlobalParameter(_actualGlobalParameter_);

    }
    public Object clone()
    {
        return new AActualGlobalParameterTail(
            (TComma) cloneNode(_comma_),
            (PActualGlobalParameter) cloneNode(_actualGlobalParameter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAActualGlobalParameterTail(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if (_comma_ != null)
        {
            _comma_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PActualGlobalParameter getActualGlobalParameter()
    {
        return _actualGlobalParameter_;
    }

    public void setActualGlobalParameter(PActualGlobalParameter node)
    {
        if (_actualGlobalParameter_ != null)
        {
            _actualGlobalParameter_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _actualGlobalParameter_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_actualGlobalParameter_);
    }

    void removeChild(Node child)
    {
        if (_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if (_actualGlobalParameter_ == child)
        {
            _actualGlobalParameter_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if (_actualGlobalParameter_ == oldChild)
        {
            setActualGlobalParameter((PActualGlobalParameter) newChild);
            return;
        }

    }
}
