/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AActualGlobalParameterList extends PActualGlobalParameterList
{
    private final LinkedList _actualGlobalParameter_ = new TypedLinkedList(new ActualGlobalParameter_Cast());

    public AActualGlobalParameterList()
    {
    }

    public AActualGlobalParameterList(
        List _actualGlobalParameter_)
    {
        {
            this._actualGlobalParameter_.clear();
            this._actualGlobalParameter_.addAll(_actualGlobalParameter_);
        }

    }

    public AActualGlobalParameterList(
        XPActualGlobalParameter _actualGlobalParameter_)
    {
        if (_actualGlobalParameter_ != null)
        {
            while (_actualGlobalParameter_ instanceof X1PActualGlobalParameter)
            {
                this._actualGlobalParameter_.addFirst(((X1PActualGlobalParameter) _actualGlobalParameter_).getPActualGlobalParameter());
                _actualGlobalParameter_ = ((X1PActualGlobalParameter) _actualGlobalParameter_).getXPActualGlobalParameter();
            }
            this._actualGlobalParameter_.addFirst(((X2PActualGlobalParameter) _actualGlobalParameter_).getPActualGlobalParameter());
        }

    }
    public Object clone()
    {
        return new AActualGlobalParameterList(
            cloneList(_actualGlobalParameter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAActualGlobalParameterList(this);
    }

    public LinkedList getActualGlobalParameter()
    {
        return _actualGlobalParameter_;
    }

    public void setActualGlobalParameter(List list)
    {
        _actualGlobalParameter_.clear();
        _actualGlobalParameter_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_actualGlobalParameter_);
    }

    void removeChild(Node child)
    {
        if (_actualGlobalParameter_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _actualGlobalParameter_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ActualGlobalParameter_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PActualGlobalParameter node = (PActualGlobalParameter) o;

            if ((node.parent() != null) &&
                (node.parent() != AActualGlobalParameterList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AActualGlobalParameterList.this))
            {
                node.parent(AActualGlobalParameterList.this);
            }

            return node;
        }
    }
}
