/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AActualScopedParameterList extends PActualScopedParameterList
{
    private final LinkedList _actualScopedParameter_ = new TypedLinkedList(new ActualScopedParameter_Cast());

    public AActualScopedParameterList()
    {
    }

    public AActualScopedParameterList(
        List _actualScopedParameter_)
    {
        {
            this._actualScopedParameter_.clear();
            this._actualScopedParameter_.addAll(_actualScopedParameter_);
        }

    }

    public AActualScopedParameterList(
        XPActualScopedParameter _actualScopedParameter_)
    {
        if (_actualScopedParameter_ != null)
        {
            while (_actualScopedParameter_ instanceof X1PActualScopedParameter)
            {
                this._actualScopedParameter_.addFirst(((X1PActualScopedParameter) _actualScopedParameter_).getPActualScopedParameter());
                _actualScopedParameter_ = ((X1PActualScopedParameter) _actualScopedParameter_).getXPActualScopedParameter();
            }
            this._actualScopedParameter_.addFirst(((X2PActualScopedParameter) _actualScopedParameter_).getPActualScopedParameter());
        }

    }
    public Object clone()
    {
        return new AActualScopedParameterList(
            cloneList(_actualScopedParameter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAActualScopedParameterList(this);
    }

    public LinkedList getActualScopedParameter()
    {
        return _actualScopedParameter_;
    }

    public void setActualScopedParameter(List list)
    {
        _actualScopedParameter_.clear();
        _actualScopedParameter_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_actualScopedParameter_);
    }

    void removeChild(Node child)
    {
        if (_actualScopedParameter_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _actualScopedParameter_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ActualScopedParameter_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PActualScopedParameter node = (PActualScopedParameter) o;

            if ((node.parent() != null) &&
                (node.parent() != AActualScopedParameterList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AActualScopedParameterList.this))
            {
                node.parent(AActualScopedParameterList.this);
            }

            return node;
        }
    }
}
