/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AConcreteActualGlobalParameterList extends PActualGlobalParameterList
{
    private PActualGlobalParameter _actualGlobalParameter_;
    private final LinkedList _actualGlobalParameterTail_ = new TypedLinkedList(new ActualGlobalParameterTail_Cast());

    public AConcreteActualGlobalParameterList()
    {
    }

    public AConcreteActualGlobalParameterList(
        PActualGlobalParameter _actualGlobalParameter_,
        List _actualGlobalParameterTail_)
    {
        setActualGlobalParameter(_actualGlobalParameter_);

        {
            this._actualGlobalParameterTail_.clear();
            this._actualGlobalParameterTail_.addAll(_actualGlobalParameterTail_);
        }

    }

    public AConcreteActualGlobalParameterList(
        PActualGlobalParameter _actualGlobalParameter_,
        XPActualGlobalParameterTail _actualGlobalParameterTail_)
    {
        setActualGlobalParameter(_actualGlobalParameter_);

        if (_actualGlobalParameterTail_ != null)
        {
            while (_actualGlobalParameterTail_ instanceof X1PActualGlobalParameterTail)
            {
                this._actualGlobalParameterTail_.addFirst(((X1PActualGlobalParameterTail) _actualGlobalParameterTail_).getPActualGlobalParameterTail());
                _actualGlobalParameterTail_ = ((X1PActualGlobalParameterTail) _actualGlobalParameterTail_).getXPActualGlobalParameterTail();
            }
            this._actualGlobalParameterTail_.addFirst(((X2PActualGlobalParameterTail) _actualGlobalParameterTail_).getPActualGlobalParameterTail());
        }

    }
    public Object clone()
    {
        return new AConcreteActualGlobalParameterList(
            (PActualGlobalParameter) cloneNode(_actualGlobalParameter_),
            cloneList(_actualGlobalParameterTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcreteActualGlobalParameterList(this);
    }

    public PActualGlobalParameter getActualGlobalParameter()
    {
        return _actualGlobalParameter_;
    }

    public void setActualGlobalParameter(PActualGlobalParameter node)
    {
        if (_actualGlobalParameter_ != null)
        {
            _actualGlobalParameter_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _actualGlobalParameter_ = node;
    }

    public LinkedList getActualGlobalParameterTail()
    {
        return _actualGlobalParameterTail_;
    }

    public void setActualGlobalParameterTail(List list)
    {
        _actualGlobalParameterTail_.clear();
        _actualGlobalParameterTail_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_actualGlobalParameter_)
            + toString(_actualGlobalParameterTail_);
    }

    void removeChild(Node child)
    {
        if (_actualGlobalParameter_ == child)
        {
            _actualGlobalParameter_ = null;
            return;
        }

        if (_actualGlobalParameterTail_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_actualGlobalParameter_ == oldChild)
        {
            setActualGlobalParameter((PActualGlobalParameter) newChild);
            return;
        }

        for (ListIterator i = _actualGlobalParameterTail_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ActualGlobalParameterTail_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PActualGlobalParameterTail node = (PActualGlobalParameterTail) o;

            if ((node.parent() != null) &&
                (node.parent() != AConcreteActualGlobalParameterList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AConcreteActualGlobalParameterList.this))
            {
                node.parent(AConcreteActualGlobalParameterList.this);
            }

            return node;
        }
    }
}
