/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AConcreteNetworkTimeslotDeclarationList extends PNetworkTimeslotDeclarationList
{
    private PNetworkTimeslotDeclaration _networkTimeslotDeclaration_;
    private final LinkedList _networkTimeslotDeclarationTail_ = new TypedLinkedList(new NetworkTimeslotDeclarationTail_Cast());

    public AConcreteNetworkTimeslotDeclarationList()
    {
    }

    public AConcreteNetworkTimeslotDeclarationList(
        PNetworkTimeslotDeclaration _networkTimeslotDeclaration_,
        List _networkTimeslotDeclarationTail_)
    {
        setNetworkTimeslotDeclaration(_networkTimeslotDeclaration_);

        {
            this._networkTimeslotDeclarationTail_.clear();
            this._networkTimeslotDeclarationTail_.addAll(_networkTimeslotDeclarationTail_);
        }

    }

    public AConcreteNetworkTimeslotDeclarationList(
        PNetworkTimeslotDeclaration _networkTimeslotDeclaration_,
        XPNetworkTimeslotDeclarationTail _networkTimeslotDeclarationTail_)
    {
        setNetworkTimeslotDeclaration(_networkTimeslotDeclaration_);

        if (_networkTimeslotDeclarationTail_ != null)
        {
            while (_networkTimeslotDeclarationTail_ instanceof X1PNetworkTimeslotDeclarationTail)
            {
                this._networkTimeslotDeclarationTail_.addFirst(((X1PNetworkTimeslotDeclarationTail) _networkTimeslotDeclarationTail_).getPNetworkTimeslotDeclarationTail());
                _networkTimeslotDeclarationTail_ = ((X1PNetworkTimeslotDeclarationTail) _networkTimeslotDeclarationTail_).getXPNetworkTimeslotDeclarationTail();
            }
            this._networkTimeslotDeclarationTail_.addFirst(((X2PNetworkTimeslotDeclarationTail) _networkTimeslotDeclarationTail_).getPNetworkTimeslotDeclarationTail());
        }

    }
    public Object clone()
    {
        return new AConcreteNetworkTimeslotDeclarationList(
            (PNetworkTimeslotDeclaration) cloneNode(_networkTimeslotDeclaration_),
            cloneList(_networkTimeslotDeclarationTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcreteNetworkTimeslotDeclarationList(this);
    }

    public PNetworkTimeslotDeclaration getNetworkTimeslotDeclaration()
    {
        return _networkTimeslotDeclaration_;
    }

    public void setNetworkTimeslotDeclaration(PNetworkTimeslotDeclaration node)
    {
        if (_networkTimeslotDeclaration_ != null)
        {
            _networkTimeslotDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _networkTimeslotDeclaration_ = node;
    }

    public LinkedList getNetworkTimeslotDeclarationTail()
    {
        return _networkTimeslotDeclarationTail_;
    }

    public void setNetworkTimeslotDeclarationTail(List list)
    {
        _networkTimeslotDeclarationTail_.clear();
        _networkTimeslotDeclarationTail_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_networkTimeslotDeclaration_)
            + toString(_networkTimeslotDeclarationTail_);
    }

    void removeChild(Node child)
    {
        if (_networkTimeslotDeclaration_ == child)
        {
            _networkTimeslotDeclaration_ = null;
            return;
        }

        if (_networkTimeslotDeclarationTail_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_networkTimeslotDeclaration_ == oldChild)
        {
            setNetworkTimeslotDeclaration((PNetworkTimeslotDeclaration) newChild);
            return;
        }

        for (ListIterator i = _networkTimeslotDeclarationTail_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class NetworkTimeslotDeclarationTail_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PNetworkTimeslotDeclarationTail node = (PNetworkTimeslotDeclarationTail) o;

            if ((node.parent() != null) &&
                (node.parent() != AConcreteNetworkTimeslotDeclarationList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AConcreteNetworkTimeslotDeclarationList.this))
            {
                node.parent(AConcreteNetworkTimeslotDeclarationList.this);
            }

            return node;
        }
    }
}
