/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class ADestinations extends PDestinations
{
    private TTo _to_;
    private TLPar _lPar_;
    private PHostList _destinationNames_;
    private TRPar _rPar_;

    public ADestinations()
    {
    }

    public ADestinations(
        TTo _to_,
        TLPar _lPar_,
        PHostList _destinationNames_,
        TRPar _rPar_)
    {
        setTo(_to_);

        setLPar(_lPar_);

        setDestinationNames(_destinationNames_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new ADestinations(
            (TTo) cloneNode(_to_),
            (TLPar) cloneNode(_lPar_),
            (PHostList) cloneNode(_destinationNames_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADestinations(this);
    }

    public TTo getTo()
    {
        return _to_;
    }

    public void setTo(TTo node)
    {
        if (_to_ != null)
        {
            _to_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _to_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if (_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PHostList getDestinationNames()
    {
        return _destinationNames_;
    }

    public void setDestinationNames(PHostList node)
    {
        if (_destinationNames_ != null)
        {
            _destinationNames_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _destinationNames_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if (_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_to_)
            + toString(_lPar_)
            + toString(_destinationNames_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if (_to_ == child)
        {
            _to_ = null;
            return;
        }

        if (_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if (_destinationNames_ == child)
        {
            _destinationNames_ = null;
            return;
        }

        if (_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_to_ == oldChild)
        {
            setTo((TTo) newChild);
            return;
        }

        if (_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if (_destinationNames_ == oldChild)
        {
            setDestinationNames((PHostList) newChild);
            return;
        }

        if (_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
