/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AHardwareDeclarationList extends PHardwareDeclarationList
{
    private final LinkedList _hardwareDeclaration_ = new TypedLinkedList(new HardwareDeclaration_Cast());

    public AHardwareDeclarationList()
    {
    }

    public AHardwareDeclarationList(
        List _hardwareDeclaration_)
    {
        {
            this._hardwareDeclaration_.clear();
            this._hardwareDeclaration_.addAll(_hardwareDeclaration_);
        }

    }

    public AHardwareDeclarationList(
        XPHardwareDeclaration _hardwareDeclaration_)
    {
        if (_hardwareDeclaration_ != null)
        {
            while (_hardwareDeclaration_ instanceof X1PHardwareDeclaration)
            {
                this._hardwareDeclaration_.addFirst(((X1PHardwareDeclaration) _hardwareDeclaration_).getPHardwareDeclaration());
                _hardwareDeclaration_ = ((X1PHardwareDeclaration) _hardwareDeclaration_).getXPHardwareDeclaration();
            }
            this._hardwareDeclaration_.addFirst(((X2PHardwareDeclaration) _hardwareDeclaration_).getPHardwareDeclaration());
        }

    }
    public Object clone()
    {
        return new AHardwareDeclarationList(
            cloneList(_hardwareDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHardwareDeclarationList(this);
    }

    public LinkedList getHardwareDeclaration()
    {
        return _hardwareDeclaration_;
    }

    public void setHardwareDeclaration(List list)
    {
        _hardwareDeclaration_.clear();
        _hardwareDeclaration_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_hardwareDeclaration_);
    }

    void removeChild(Node child)
    {
        if (_hardwareDeclaration_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _hardwareDeclaration_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class HardwareDeclaration_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PHardwareDeclaration node = (PHardwareDeclaration) o;

            if ((node.parent() != null) &&
                (node.parent() != AHardwareDeclarationList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AHardwareDeclarationList.this))
            {
                node.parent(AHardwareDeclarationList.this);
            }

            return node;
        }
    }
}
