/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AHostList extends PHostList
{
    private final LinkedList _hostNameIdent_ = new TypedLinkedList(new HostNameIdent_Cast());

    public AHostList()
    {
    }

    public AHostList(
        List _hostNameIdent_)
    {
        {
            this._hostNameIdent_.clear();
            this._hostNameIdent_.addAll(_hostNameIdent_);
        }

    }

    public AHostList(
        XPHostNameIdent _hostNameIdent_)
    {
        if (_hostNameIdent_ != null)
        {
            while (_hostNameIdent_ instanceof X1PHostNameIdent)
            {
                this._hostNameIdent_.addFirst(((X1PHostNameIdent) _hostNameIdent_).getPHostNameIdent());
                _hostNameIdent_ = ((X1PHostNameIdent) _hostNameIdent_).getXPHostNameIdent();
            }
            this._hostNameIdent_.addFirst(((X2PHostNameIdent) _hostNameIdent_).getPHostNameIdent());
        }

    }
    public Object clone()
    {
        return new AHostList(
            cloneList(_hostNameIdent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHostList(this);
    }

    public LinkedList getHostNameIdent()
    {
        return _hostNameIdent_;
    }

    public void setHostNameIdent(List list)
    {
        _hostNameIdent_.clear();
        _hostNameIdent_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_hostNameIdent_);
    }

    void removeChild(Node child)
    {
        if (_hostNameIdent_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _hostNameIdent_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class HostNameIdent_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PHostNameIdent node = (PHostNameIdent) o;

            if ((node.parent() != null) &&
                (node.parent() != AHostList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AHostList.this))
            {
                node.parent(AHostList.this);
            }

            return node;
        }
    }
}
