/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AIP extends PIP
{
    private TNumber _octet1_;
    private TDot _dot1_;
    private TNumber _octet2_;
    private TDot _dot2_;
    private TNumber _octet3_;
    private TDot _dot3_;
    private TNumber _octet4_;

    public AIP()
    {
    }

    public AIP(
        TNumber _octet1_,
        TDot _dot1_,
        TNumber _octet2_,
        TDot _dot2_,
        TNumber _octet3_,
        TDot _dot3_,
        TNumber _octet4_)
    {
        setOctet1(_octet1_);

        setDot1(_dot1_);

        setOctet2(_octet2_);

        setDot2(_dot2_);

        setOctet3(_octet3_);

        setDot3(_dot3_);

        setOctet4(_octet4_);

    }
    public Object clone()
    {
        return new AIP(
            (TNumber) cloneNode(_octet1_),
            (TDot) cloneNode(_dot1_),
            (TNumber) cloneNode(_octet2_),
            (TDot) cloneNode(_dot2_),
            (TNumber) cloneNode(_octet3_),
            (TDot) cloneNode(_dot3_),
            (TNumber) cloneNode(_octet4_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIP(this);
    }

    public TNumber getOctet1()
    {
        return _octet1_;
    }

    public void setOctet1(TNumber node)
    {
        if (_octet1_ != null)
        {
            _octet1_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _octet1_ = node;
    }

    public TDot getDot1()
    {
        return _dot1_;
    }

    public void setDot1(TDot node)
    {
        if (_dot1_ != null)
        {
            _dot1_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dot1_ = node;
    }

    public TNumber getOctet2()
    {
        return _octet2_;
    }

    public void setOctet2(TNumber node)
    {
        if (_octet2_ != null)
        {
            _octet2_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _octet2_ = node;
    }

    public TDot getDot2()
    {
        return _dot2_;
    }

    public void setDot2(TDot node)
    {
        if (_dot2_ != null)
        {
            _dot2_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dot2_ = node;
    }

    public TNumber getOctet3()
    {
        return _octet3_;
    }

    public void setOctet3(TNumber node)
    {
        if (_octet3_ != null)
        {
            _octet3_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _octet3_ = node;
    }

    public TDot getDot3()
    {
        return _dot3_;
    }

    public void setDot3(TDot node)
    {
        if (_dot3_ != null)
        {
            _dot3_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dot3_ = node;
    }

    public TNumber getOctet4()
    {
        return _octet4_;
    }

    public void setOctet4(TNumber node)
    {
        if (_octet4_ != null)
        {
            _octet4_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _octet4_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_octet1_)
            + toString(_dot1_)
            + toString(_octet2_)
            + toString(_dot2_)
            + toString(_octet3_)
            + toString(_dot3_)
            + toString(_octet4_);
    }

    void removeChild(Node child)
    {
        if (_octet1_ == child)
        {
            _octet1_ = null;
            return;
        }

        if (_dot1_ == child)
        {
            _dot1_ = null;
            return;
        }

        if (_octet2_ == child)
        {
            _octet2_ = null;
            return;
        }

        if (_dot2_ == child)
        {
            _dot2_ = null;
            return;
        }

        if (_octet3_ == child)
        {
            _octet3_ = null;
            return;
        }

        if (_dot3_ == child)
        {
            _dot3_ = null;
            return;
        }

        if (_octet4_ == child)
        {
            _octet4_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_octet1_ == oldChild)
        {
            setOctet1((TNumber) newChild);
            return;
        }

        if (_dot1_ == oldChild)
        {
            setDot1((TDot) newChild);
            return;
        }

        if (_octet2_ == oldChild)
        {
            setOctet2((TNumber) newChild);
            return;
        }

        if (_dot2_ == oldChild)
        {
            setDot2((TDot) newChild);
            return;
        }

        if (_octet3_ == oldChild)
        {
            setOctet3((TNumber) newChild);
            return;
        }

        if (_dot3_ == oldChild)
        {
            setDot3((TDot) newChild);
            return;
        }

        if (_octet4_ == oldChild)
        {
            setOctet4((TNumber) newChild);
            return;
        }

    }
}
