/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AModuleDeclarationTail extends PModuleDeclarationTail
{
    private TComma _comma_;
    private PModuleDeclaration _moduleDeclaration_;

    public AModuleDeclarationTail()
    {
    }

    public AModuleDeclarationTail(
        TComma _comma_,
        PModuleDeclaration _moduleDeclaration_)
    {
        setComma(_comma_);

        setModuleDeclaration(_moduleDeclaration_);

    }
    public Object clone()
    {
        return new AModuleDeclarationTail(
            (TComma) cloneNode(_comma_),
            (PModuleDeclaration) cloneNode(_moduleDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuleDeclarationTail(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if (_comma_ != null)
        {
            _comma_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PModuleDeclaration getModuleDeclaration()
    {
        return _moduleDeclaration_;
    }

    public void setModuleDeclaration(PModuleDeclaration node)
    {
        if (_moduleDeclaration_ != null)
        {
            _moduleDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _moduleDeclaration_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_moduleDeclaration_);
    }

    void removeChild(Node child)
    {
        if (_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if (_moduleDeclaration_ == child)
        {
            _moduleDeclaration_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if (_moduleDeclaration_ == oldChild)
        {
            setModuleDeclaration((PModuleDeclaration) newChild);
            return;
        }

    }
}
