/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AModuleDeclaration extends PModuleDeclaration
{
    private TIdent _moduleName_;

    public AModuleDeclaration()
    {
    }

    public AModuleDeclaration(
        TIdent _moduleName_)
    {
        setModuleName(_moduleName_);

    }
    public Object clone()
    {
        return new AModuleDeclaration(
            (TIdent) cloneNode(_moduleName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuleDeclaration(this);
    }

    public TIdent getModuleName()
    {
        return _moduleName_;
    }

    public void setModuleName(TIdent node)
    {
        if (_moduleName_ != null)
        {
            _moduleName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _moduleName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_moduleName_);
    }

    void removeChild(Node child)
    {
        if (_moduleName_ == child)
        {
            _moduleName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_moduleName_ == oldChild)
        {
            setModuleName((TIdent) newChild);
            return;
        }

    }
}
