/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AModeSwitch extends PModeSwitch
{
    private TExitfreq _exitfreq_;
    private TNumber _modeSwitchFrequency_;
    private TDo _do_;
    private TIdent _modeName_;
    private TLPar _lPar_;
    private TIdent _driverName_;
    private TRPar _rPar_;
    private PModeSwitchAnnotation _modeSwitchAnnotation_;
    private TSemicolon _semicolon_;

    public AModeSwitch()
    {
    }

    public AModeSwitch(
        TExitfreq _exitfreq_,
        TNumber _modeSwitchFrequency_,
        TDo _do_,
        TIdent _modeName_,
        TLPar _lPar_,
        TIdent _driverName_,
        TRPar _rPar_,
        PModeSwitchAnnotation _modeSwitchAnnotation_,
        TSemicolon _semicolon_)
    {
        setExitfreq(_exitfreq_);

        setModeSwitchFrequency(_modeSwitchFrequency_);

        setDo(_do_);

        setModeName(_modeName_);

        setLPar(_lPar_);

        setDriverName(_driverName_);

        setRPar(_rPar_);

        setModeSwitchAnnotation(_modeSwitchAnnotation_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new AModeSwitch(
            (TExitfreq) cloneNode(_exitfreq_),
            (TNumber) cloneNode(_modeSwitchFrequency_),
            (TDo) cloneNode(_do_),
            (TIdent) cloneNode(_modeName_),
            (TLPar) cloneNode(_lPar_),
            (TIdent) cloneNode(_driverName_),
            (TRPar) cloneNode(_rPar_),
            (PModeSwitchAnnotation) cloneNode(_modeSwitchAnnotation_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModeSwitch(this);
    }

    public TExitfreq getExitfreq()
    {
        return _exitfreq_;
    }

    public void setExitfreq(TExitfreq node)
    {
        if (_exitfreq_ != null)
        {
            _exitfreq_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exitfreq_ = node;
    }

    public TNumber getModeSwitchFrequency()
    {
        return _modeSwitchFrequency_;
    }

    public void setModeSwitchFrequency(TNumber node)
    {
        if (_modeSwitchFrequency_ != null)
        {
            _modeSwitchFrequency_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _modeSwitchFrequency_ = node;
    }

    public TDo getDo()
    {
        return _do_;
    }

    public void setDo(TDo node)
    {
        if (_do_ != null)
        {
            _do_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _do_ = node;
    }

    public TIdent getModeName()
    {
        return _modeName_;
    }

    public void setModeName(TIdent node)
    {
        if (_modeName_ != null)
        {
            _modeName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _modeName_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if (_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public TIdent getDriverName()
    {
        return _driverName_;
    }

    public void setDriverName(TIdent node)
    {
        if (_driverName_ != null)
        {
            _driverName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _driverName_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if (_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PModeSwitchAnnotation getModeSwitchAnnotation()
    {
        return _modeSwitchAnnotation_;
    }

    public void setModeSwitchAnnotation(PModeSwitchAnnotation node)
    {
        if (_modeSwitchAnnotation_ != null)
        {
            _modeSwitchAnnotation_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _modeSwitchAnnotation_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if (_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exitfreq_)
            + toString(_modeSwitchFrequency_)
            + toString(_do_)
            + toString(_modeName_)
            + toString(_lPar_)
            + toString(_driverName_)
            + toString(_rPar_)
            + toString(_modeSwitchAnnotation_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if (_exitfreq_ == child)
        {
            _exitfreq_ = null;
            return;
        }

        if (_modeSwitchFrequency_ == child)
        {
            _modeSwitchFrequency_ = null;
            return;
        }

        if (_do_ == child)
        {
            _do_ = null;
            return;
        }

        if (_modeName_ == child)
        {
            _modeName_ = null;
            return;
        }

        if (_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if (_driverName_ == child)
        {
            _driverName_ = null;
            return;
        }

        if (_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if (_modeSwitchAnnotation_ == child)
        {
            _modeSwitchAnnotation_ = null;
            return;
        }

        if (_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_exitfreq_ == oldChild)
        {
            setExitfreq((TExitfreq) newChild);
            return;
        }

        if (_modeSwitchFrequency_ == oldChild)
        {
            setModeSwitchFrequency((TNumber) newChild);
            return;
        }

        if (_do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if (_modeName_ == oldChild)
        {
            setModeName((TIdent) newChild);
            return;
        }

        if (_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if (_driverName_ == oldChild)
        {
            setDriverName((TIdent) newChild);
            return;
        }

        if (_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if (_modeSwitchAnnotation_ == oldChild)
        {
            setModeSwitchAnnotation((PModeSwitchAnnotation) newChild);
            return;
        }

        if (_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
