/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class ANetworkTimeslotDeclarationList extends PNetworkTimeslotDeclarationList
{
    private final LinkedList _networkTimeslotDeclaration_ = new TypedLinkedList(new NetworkTimeslotDeclaration_Cast());

    public ANetworkTimeslotDeclarationList()
    {
    }

    public ANetworkTimeslotDeclarationList(
        List _networkTimeslotDeclaration_)
    {
        {
            this._networkTimeslotDeclaration_.clear();
            this._networkTimeslotDeclaration_.addAll(_networkTimeslotDeclaration_);
        }

    }

    public ANetworkTimeslotDeclarationList(
        XPNetworkTimeslotDeclaration _networkTimeslotDeclaration_)
    {
        if (_networkTimeslotDeclaration_ != null)
        {
            while (_networkTimeslotDeclaration_ instanceof X1PNetworkTimeslotDeclaration)
            {
                this._networkTimeslotDeclaration_.addFirst(((X1PNetworkTimeslotDeclaration) _networkTimeslotDeclaration_).getPNetworkTimeslotDeclaration());
                _networkTimeslotDeclaration_ = ((X1PNetworkTimeslotDeclaration) _networkTimeslotDeclaration_).getXPNetworkTimeslotDeclaration();
            }
            this._networkTimeslotDeclaration_.addFirst(((X2PNetworkTimeslotDeclaration) _networkTimeslotDeclaration_).getPNetworkTimeslotDeclaration());
        }

    }
    public Object clone()
    {
        return new ANetworkTimeslotDeclarationList(
            cloneList(_networkTimeslotDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANetworkTimeslotDeclarationList(this);
    }

    public LinkedList getNetworkTimeslotDeclaration()
    {
        return _networkTimeslotDeclaration_;
    }

    public void setNetworkTimeslotDeclaration(List list)
    {
        _networkTimeslotDeclaration_.clear();
        _networkTimeslotDeclaration_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_networkTimeslotDeclaration_);
    }

    void removeChild(Node child)
    {
        if (_networkTimeslotDeclaration_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _networkTimeslotDeclaration_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class NetworkTimeslotDeclaration_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PNetworkTimeslotDeclaration node = (PNetworkTimeslotDeclaration) o;

            if ((node.parent() != null) &&
                (node.parent() != ANetworkTimeslotDeclarationList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != ANetworkTimeslotDeclarationList.this))
            {
                node.parent(ANetworkTimeslotDeclarationList.this);
            }

            return node;
        }
    }
}
