/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class ANetworkTimeslots extends PNetworkTimeslots
{
    private TIn _in_;
    private PNetworkNameIdent _networkName_;
    private TSlots _slots_;
    private PTimeslotList _timeslotList_;

    public ANetworkTimeslots()
    {
    }

    public ANetworkTimeslots(
        TIn _in_,
        PNetworkNameIdent _networkName_,
        TSlots _slots_,
        PTimeslotList _timeslotList_)
    {
        setIn(_in_);

        setNetworkName(_networkName_);

        setSlots(_slots_);

        setTimeslotList(_timeslotList_);

    }
    public Object clone()
    {
        return new ANetworkTimeslots(
            (TIn) cloneNode(_in_),
            (PNetworkNameIdent) cloneNode(_networkName_),
            (TSlots) cloneNode(_slots_),
            (PTimeslotList) cloneNode(_timeslotList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANetworkTimeslots(this);
    }

    public TIn getIn()
    {
        return _in_;
    }

    public void setIn(TIn node)
    {
        if (_in_ != null)
        {
            _in_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _in_ = node;
    }

    public PNetworkNameIdent getNetworkName()
    {
        return _networkName_;
    }

    public void setNetworkName(PNetworkNameIdent node)
    {
        if (_networkName_ != null)
        {
            _networkName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _networkName_ = node;
    }

    public TSlots getSlots()
    {
        return _slots_;
    }

    public void setSlots(TSlots node)
    {
        if (_slots_ != null)
        {
            _slots_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _slots_ = node;
    }

    public PTimeslotList getTimeslotList()
    {
        return _timeslotList_;
    }

    public void setTimeslotList(PTimeslotList node)
    {
        if (_timeslotList_ != null)
        {
            _timeslotList_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _timeslotList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_in_)
            + toString(_networkName_)
            + toString(_slots_)
            + toString(_timeslotList_);
    }

    void removeChild(Node child)
    {
        if (_in_ == child)
        {
            _in_ = null;
            return;
        }

        if (_networkName_ == child)
        {
            _networkName_ = null;
            return;
        }

        if (_slots_ == child)
        {
            _slots_ = null;
            return;
        }

        if (_timeslotList_ == child)
        {
            _timeslotList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_in_ == oldChild)
        {
            setIn((TIn) newChild);
            return;
        }

        if (_networkName_ == oldChild)
        {
            setNetworkName((PNetworkNameIdent) newChild);
            return;
        }

        if (_slots_ == oldChild)
        {
            setSlots((TSlots) newChild);
            return;
        }

        if (_timeslotList_ == oldChild)
        {
            setTimeslotList((PTimeslotList) newChild);
            return;
        }

    }
}
