/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class ANetworkTimeslotDeclaration extends PNetworkTimeslotDeclaration
{
    private TNetwork _network_;
    private PNetworkNameIdent _networkName_;
    private TSlots _slots_;
    private PTimeslotDeclarationList _timeslotDeclarationList_;

    public ANetworkTimeslotDeclaration()
    {
    }

    public ANetworkTimeslotDeclaration(
        TNetwork _network_,
        PNetworkNameIdent _networkName_,
        TSlots _slots_,
        PTimeslotDeclarationList _timeslotDeclarationList_)
    {
        setNetwork(_network_);

        setNetworkName(_networkName_);

        setSlots(_slots_);

        setTimeslotDeclarationList(_timeslotDeclarationList_);

    }
    public Object clone()
    {
        return new ANetworkTimeslotDeclaration(
            (TNetwork) cloneNode(_network_),
            (PNetworkNameIdent) cloneNode(_networkName_),
            (TSlots) cloneNode(_slots_),
            (PTimeslotDeclarationList) cloneNode(_timeslotDeclarationList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANetworkTimeslotDeclaration(this);
    }

    public TNetwork getNetwork()
    {
        return _network_;
    }

    public void setNetwork(TNetwork node)
    {
        if (_network_ != null)
        {
            _network_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _network_ = node;
    }

    public PNetworkNameIdent getNetworkName()
    {
        return _networkName_;
    }

    public void setNetworkName(PNetworkNameIdent node)
    {
        if (_networkName_ != null)
        {
            _networkName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _networkName_ = node;
    }

    public TSlots getSlots()
    {
        return _slots_;
    }

    public void setSlots(TSlots node)
    {
        if (_slots_ != null)
        {
            _slots_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _slots_ = node;
    }

    public PTimeslotDeclarationList getTimeslotDeclarationList()
    {
        return _timeslotDeclarationList_;
    }

    public void setTimeslotDeclarationList(PTimeslotDeclarationList node)
    {
        if (_timeslotDeclarationList_ != null)
        {
            _timeslotDeclarationList_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _timeslotDeclarationList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_network_)
            + toString(_networkName_)
            + toString(_slots_)
            + toString(_timeslotDeclarationList_);
    }

    void removeChild(Node child)
    {
        if (_network_ == child)
        {
            _network_ = null;
            return;
        }

        if (_networkName_ == child)
        {
            _networkName_ = null;
            return;
        }

        if (_slots_ == child)
        {
            _slots_ = null;
            return;
        }

        if (_timeslotDeclarationList_ == child)
        {
            _timeslotDeclarationList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_network_ == oldChild)
        {
            setNetwork((TNetwork) newChild);
            return;
        }

        if (_networkName_ == oldChild)
        {
            setNetworkName((PNetworkNameIdent) newChild);
            return;
        }

        if (_slots_ == oldChild)
        {
            setSlots((TSlots) newChild);
            return;
        }

        if (_timeslotDeclarationList_ == oldChild)
        {
            setTimeslotDeclarationList((PTimeslotDeclarationList) newChild);
            return;
        }

    }
}
