/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class APriorityList extends PPriorityList
{
    private final LinkedList _priorityProd_ = new TypedLinkedList(new PriorityProd_Cast());

    public APriorityList()
    {
    }

    public APriorityList(
        List _priorityProd_)
    {
        {
            this._priorityProd_.clear();
            this._priorityProd_.addAll(_priorityProd_);
        }

    }

    public APriorityList(
        XPPriorityProd _priorityProd_)
    {
        if (_priorityProd_ != null)
        {
            while (_priorityProd_ instanceof X1PPriorityProd)
            {
                this._priorityProd_.addFirst(((X1PPriorityProd) _priorityProd_).getPPriorityProd());
                _priorityProd_ = ((X1PPriorityProd) _priorityProd_).getXPPriorityProd();
            }
            this._priorityProd_.addFirst(((X2PPriorityProd) _priorityProd_).getPPriorityProd());
        }

    }
    public Object clone()
    {
        return new APriorityList(
            cloneList(_priorityProd_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPriorityList(this);
    }

    public LinkedList getPriorityProd()
    {
        return _priorityProd_;
    }

    public void setPriorityProd(List list)
    {
        _priorityProd_.clear();
        _priorityProd_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_priorityProd_);
    }

    void removeChild(Node child)
    {
        if (_priorityProd_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _priorityProd_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class PriorityProd_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PPriorityProd node = (PPriorityProd) o;

            if ((node.parent() != null) &&
                (node.parent() != APriorityList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != APriorityList.this))
            {
                node.parent(APriorityList.this);
            }

            return node;
        }
    }
}
