/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class AScheduleConnectionList extends PScheduleConnectionList
{
    private final LinkedList _scheduleConnection_ = new TypedLinkedList(new ScheduleConnection_Cast());

    public AScheduleConnectionList()
    {
    }

    public AScheduleConnectionList(
        List _scheduleConnection_)
    {
        {
            this._scheduleConnection_.clear();
            this._scheduleConnection_.addAll(_scheduleConnection_);
        }

    }

    public AScheduleConnectionList(
        XPScheduleConnection _scheduleConnection_)
    {
        if (_scheduleConnection_ != null)
        {
            while (_scheduleConnection_ instanceof X1PScheduleConnection)
            {
                this._scheduleConnection_.addFirst(((X1PScheduleConnection) _scheduleConnection_).getPScheduleConnection());
                _scheduleConnection_ = ((X1PScheduleConnection) _scheduleConnection_).getXPScheduleConnection();
            }
            this._scheduleConnection_.addFirst(((X2PScheduleConnection) _scheduleConnection_).getPScheduleConnection());
        }

    }
    public Object clone()
    {
        return new AScheduleConnectionList(
            cloneList(_scheduleConnection_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScheduleConnectionList(this);
    }

    public LinkedList getScheduleConnection()
    {
        return _scheduleConnection_;
    }

    public void setScheduleConnection(List list)
    {
        _scheduleConnection_.clear();
        _scheduleConnection_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_scheduleConnection_);
    }

    void removeChild(Node child)
    {
        if (_scheduleConnection_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _scheduleConnection_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ScheduleConnection_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PScheduleConnection node = (PScheduleConnection) o;

            if ((node.parent() != null) &&
                (node.parent() != AScheduleConnectionList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != AScheduleConnectionList.this))
            {
                node.parent(AScheduleConnectionList.this);
            }

            return node;
        }
    }
}
