/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class AStatePortTail extends PStatePortTail
{
    private TComma _comma_;
    private PStatePort _statePort_;

    public AStatePortTail()
    {
    }

    public AStatePortTail(
        TComma _comma_,
        PStatePort _statePort_)
    {
        setComma(_comma_);

        setStatePort(_statePort_);

    }
    public Object clone()
    {
        return new AStatePortTail(
            (TComma) cloneNode(_comma_),
            (PStatePort) cloneNode(_statePort_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatePortTail(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if (_comma_ != null)
        {
            _comma_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PStatePort getStatePort()
    {
        return _statePort_;
    }

    public void setStatePort(PStatePort node)
    {
        if (_statePort_ != null)
        {
            _statePort_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statePort_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_statePort_);
    }

    void removeChild(Node child)
    {
        if (_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if (_statePort_ == child)
        {
            _statePort_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if (_statePort_ == oldChild)
        {
            setStatePort((PStatePort) newChild);
            return;
        }

    }
}
