/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class ATimeslotDeclarationList extends PTimeslotDeclarationList
{
    private final LinkedList _timeslotDeclaration_ = new TypedLinkedList(new TimeslotDeclaration_Cast());

    public ATimeslotDeclarationList()
    {
    }

    public ATimeslotDeclarationList(
        List _timeslotDeclaration_)
    {
        {
            this._timeslotDeclaration_.clear();
            this._timeslotDeclaration_.addAll(_timeslotDeclaration_);
        }

    }

    public ATimeslotDeclarationList(
        XPTimeslotDeclaration _timeslotDeclaration_)
    {
        if (_timeslotDeclaration_ != null)
        {
            while (_timeslotDeclaration_ instanceof X1PTimeslotDeclaration)
            {
                this._timeslotDeclaration_.addFirst(((X1PTimeslotDeclaration) _timeslotDeclaration_).getPTimeslotDeclaration());
                _timeslotDeclaration_ = ((X1PTimeslotDeclaration) _timeslotDeclaration_).getXPTimeslotDeclaration();
            }
            this._timeslotDeclaration_.addFirst(((X2PTimeslotDeclaration) _timeslotDeclaration_).getPTimeslotDeclaration());
        }

    }
    public Object clone()
    {
        return new ATimeslotDeclarationList(
            cloneList(_timeslotDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeslotDeclarationList(this);
    }

    public LinkedList getTimeslotDeclaration()
    {
        return _timeslotDeclaration_;
    }

    public void setTimeslotDeclaration(List list)
    {
        _timeslotDeclaration_.clear();
        _timeslotDeclaration_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_timeslotDeclaration_);
    }

    void removeChild(Node child)
    {
        if (_timeslotDeclaration_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _timeslotDeclaration_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class TimeslotDeclaration_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PTimeslotDeclaration node = (PTimeslotDeclaration) o;

            if ((node.parent() != null) &&
                (node.parent() != ATimeslotDeclarationList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != ATimeslotDeclarationList.this))
            {
                node.parent(ATimeslotDeclarationList.this);
            }

            return node;
        }
    }
}
