/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

public final class ATimeslotList extends PTimeslotList
{
    private final LinkedList _timeslot_ = new TypedLinkedList(new Timeslot_Cast());

    public ATimeslotList()
    {
    }

    public ATimeslotList(
        List _timeslot_)
    {
        {
            this._timeslot_.clear();
            this._timeslot_.addAll(_timeslot_);
        }

    }

    public ATimeslotList(
        XPTimeslot _timeslot_)
    {
        if (_timeslot_ != null)
        {
            while (_timeslot_ instanceof X1PTimeslot)
            {
                this._timeslot_.addFirst(((X1PTimeslot) _timeslot_).getPTimeslot());
                _timeslot_ = ((X1PTimeslot) _timeslot_).getXPTimeslot();
            }
            this._timeslot_.addFirst(((X2PTimeslot) _timeslot_).getPTimeslot());
        }

    }
    public Object clone()
    {
        return new ATimeslotList(
            cloneList(_timeslot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeslotList(this);
    }

    public LinkedList getTimeslot()
    {
        return _timeslot_;
    }

    public void setTimeslot(List list)
    {
        _timeslot_.clear();
        _timeslot_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_timeslot_);
    }

    void removeChild(Node child)
    {
        if (_timeslot_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for (ListIterator i = _timeslot_.listIterator(); i.hasNext();)
        {
            if (i.next() == oldChild)
            {
                if (newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Timeslot_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PTimeslot node = (PTimeslot) o;

            if ((node.parent() != null) &&
                (node.parent() != ATimeslotList.this))
            {
                node.parent().removeChild(node);
            }

            if ((node.parent() == null) ||
                (node.parent() != ATimeslotList.this))
            {
                node.parent(ATimeslotList.this);
            }

            return node;
        }
    }
}
