/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class ATimeslot extends PTimeslot
{
    private TIdent _timeslotName_;

    public ATimeslot()
    {
    }

    public ATimeslot(
        TIdent _timeslotName_)
    {
        setTimeslotName(_timeslotName_);

    }
    public Object clone()
    {
        return new ATimeslot(
            (TIdent) cloneNode(_timeslotName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeslot(this);
    }

    public TIdent getTimeslotName()
    {
        return _timeslotName_;
    }

    public void setTimeslotName(TIdent node)
    {
        if (_timeslotName_ != null)
        {
            _timeslotName_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _timeslotName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_timeslotName_);
    }

    void removeChild(Node child)
    {
        if (_timeslotName_ == child)
        {
            _timeslotName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if (_timeslotName_ == oldChild)
        {
            setTimeslotName((TIdent) newChild);
            return;
        }

    }
}
