/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TAddress extends Token
{
    public TAddress()
    {
        super.setText("address");
    }

    public TAddress(int line, int pos)
    {
        super.setText("address");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAddress(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAddress(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAddress text.");
    }
}
