/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TConnects extends Token
{
    public TConnects()
    {
        super.setText("connects");
    }

    public TConnects(int line, int pos)
    {
        super.setText("connects");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TConnects(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConnects(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TConnects text.");
    }
}
