/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TDriver extends Token
{
    public TDriver()
    {
        super.setText("driver");
    }

    public TDriver(int line, int pos)
    {
        super.setText("driver");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDriver(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDriver(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDriver text.");
    }
}
