/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TExitfreq extends Token
{
    public TExitfreq()
    {
        super.setText("exitfreq");
    }

    public TExitfreq(int line, int pos)
    {
        super.setText("exitfreq");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TExitfreq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExitfreq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TExitfreq text.");
    }
}
