/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class THost extends Token
{
    public THost()
    {
        super.setText("host");
    }

    public THost(int line, int pos)
    {
        super.setText("host");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THost(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHost(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THost text.");
    }
}
