/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TMode extends Token
{
    public TMode()
    {
        super.setText("mode");
    }

    public TMode(int line, int pos)
    {
        super.setText("mode");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMode(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMode(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMode text.");
    }
}
