/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TNetwork extends Token
{
    public TNetwork()
    {
        super.setText("network");
    }

    public TNetwork(int line, int pos)
    {
        super.setText("network");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNetwork(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNetwork(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNetwork text.");
    }
}
