/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TOutput extends Token
{
    public TOutput()
    {
        super.setText("output");
    }

    public TOutput(int line, int pos)
    {
        super.setText("output");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOutput(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOutput(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOutput text.");
    }
}
