/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TSchedule extends Token
{
    public TSchedule()
    {
        super.setText("schedule");
    }

    public TSchedule(int line, int pos)
    {
        super.setText("schedule");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSchedule(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSchedule(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSchedule text.");
    }
}
