/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TState extends Token
{
    public TState()
    {
        super.setText("state");
    }

    public TState(int line, int pos)
    {
        super.setText("state");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TState(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTState(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TState text.");
    }
}
