/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TStart extends Token
{
    public TStart()
    {
        super.setText("start");
    }

    public TStart(int line, int pos)
    {
        super.setText("start");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStart(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TStart text.");
    }
}
