/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TTask extends Token
{
    public TTask()
    {
        super.setText("task");
    }

    public TTask(int line, int pos)
    {
        super.setText("task");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTask(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTask(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTask text.");
    }
}
