/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;

import giotto.giottoc.analysis.Analysis;

public final class TUses extends Token
{
    public TUses()
    {
        super.setText("uses");
    }

    public TUses(int line, int pos)
    {
        super.setText("uses");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TUses(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUses(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TUses text.");
    }
}
