/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PActuatorUpdate extends XPActuatorUpdate
{
    private XPActuatorUpdate _xPActuatorUpdate_;
    private PActuatorUpdate _pActuatorUpdate_;

    public X1PActuatorUpdate()
    {
    }

    public X1PActuatorUpdate(
        XPActuatorUpdate _xPActuatorUpdate_,
        PActuatorUpdate _pActuatorUpdate_)
    {
        setXPActuatorUpdate(_xPActuatorUpdate_);
        setPActuatorUpdate(_pActuatorUpdate_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPActuatorUpdate getXPActuatorUpdate()
    {
        return _xPActuatorUpdate_;
    }

    public void setXPActuatorUpdate(XPActuatorUpdate node)
    {
        if (_xPActuatorUpdate_ != null)
        {
            _xPActuatorUpdate_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPActuatorUpdate_ = node;
    }

    public PActuatorUpdate getPActuatorUpdate()
    {
        return _pActuatorUpdate_;
    }

    public void setPActuatorUpdate(PActuatorUpdate node)
    {
        if (_pActuatorUpdate_ != null)
        {
            _pActuatorUpdate_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pActuatorUpdate_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPActuatorUpdate_ == child)
        {
            _xPActuatorUpdate_ = null;
        }

        if (_pActuatorUpdate_ == child)
        {
            _pActuatorUpdate_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPActuatorUpdate_) +
            toString(_pActuatorUpdate_);
    }
}
