/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PFormalPortTail extends XPFormalPortTail
{
    private XPFormalPortTail _xPFormalPortTail_;
    private PFormalPortTail _pFormalPortTail_;

    public X1PFormalPortTail()
    {
    }

    public X1PFormalPortTail(
        XPFormalPortTail _xPFormalPortTail_,
        PFormalPortTail _pFormalPortTail_)
    {
        setXPFormalPortTail(_xPFormalPortTail_);
        setPFormalPortTail(_pFormalPortTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPFormalPortTail getXPFormalPortTail()
    {
        return _xPFormalPortTail_;
    }

    public void setXPFormalPortTail(XPFormalPortTail node)
    {
        if (_xPFormalPortTail_ != null)
        {
            _xPFormalPortTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPFormalPortTail_ = node;
    }

    public PFormalPortTail getPFormalPortTail()
    {
        return _pFormalPortTail_;
    }

    public void setPFormalPortTail(PFormalPortTail node)
    {
        if (_pFormalPortTail_ != null)
        {
            _pFormalPortTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFormalPortTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPFormalPortTail_ == child)
        {
            _xPFormalPortTail_ = null;
        }

        if (_pFormalPortTail_ == child)
        {
            _pFormalPortTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPFormalPortTail_) +
            toString(_pFormalPortTail_);
    }
}
