/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PHostNameIdent extends XPHostNameIdent
{
    private XPHostNameIdent _xPHostNameIdent_;
    private PHostNameIdent _pHostNameIdent_;

    public X1PHostNameIdent()
    {
    }

    public X1PHostNameIdent(
        XPHostNameIdent _xPHostNameIdent_,
        PHostNameIdent _pHostNameIdent_)
    {
        setXPHostNameIdent(_xPHostNameIdent_);
        setPHostNameIdent(_pHostNameIdent_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPHostNameIdent getXPHostNameIdent()
    {
        return _xPHostNameIdent_;
    }

    public void setXPHostNameIdent(XPHostNameIdent node)
    {
        if (_xPHostNameIdent_ != null)
        {
            _xPHostNameIdent_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPHostNameIdent_ = node;
    }

    public PHostNameIdent getPHostNameIdent()
    {
        return _pHostNameIdent_;
    }

    public void setPHostNameIdent(PHostNameIdent node)
    {
        if (_pHostNameIdent_ != null)
        {
            _pHostNameIdent_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pHostNameIdent_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPHostNameIdent_ == child)
        {
            _xPHostNameIdent_ = null;
        }

        if (_pHostNameIdent_ == child)
        {
            _pHostNameIdent_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPHostNameIdent_) +
            toString(_pHostNameIdent_);
    }
}
