/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PModuleDeclaration extends XPModuleDeclaration
{
    private XPModuleDeclaration _xPModuleDeclaration_;
    private PModuleDeclaration _pModuleDeclaration_;

    public X1PModuleDeclaration()
    {
    }

    public X1PModuleDeclaration(
        XPModuleDeclaration _xPModuleDeclaration_,
        PModuleDeclaration _pModuleDeclaration_)
    {
        setXPModuleDeclaration(_xPModuleDeclaration_);
        setPModuleDeclaration(_pModuleDeclaration_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPModuleDeclaration getXPModuleDeclaration()
    {
        return _xPModuleDeclaration_;
    }

    public void setXPModuleDeclaration(XPModuleDeclaration node)
    {
        if (_xPModuleDeclaration_ != null)
        {
            _xPModuleDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPModuleDeclaration_ = node;
    }

    public PModuleDeclaration getPModuleDeclaration()
    {
        return _pModuleDeclaration_;
    }

    public void setPModuleDeclaration(PModuleDeclaration node)
    {
        if (_pModuleDeclaration_ != null)
        {
            _pModuleDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pModuleDeclaration_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPModuleDeclaration_ == child)
        {
            _xPModuleDeclaration_ = null;
        }

        if (_pModuleDeclaration_ == child)
        {
            _pModuleDeclaration_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPModuleDeclaration_) +
            toString(_pModuleDeclaration_);
    }
}
