/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1POutputDeclaration extends XPOutputDeclaration
{
    private XPOutputDeclaration _xPOutputDeclaration_;
    private POutputDeclaration _pOutputDeclaration_;

    public X1POutputDeclaration()
    {
    }

    public X1POutputDeclaration(
        XPOutputDeclaration _xPOutputDeclaration_,
        POutputDeclaration _pOutputDeclaration_)
    {
        setXPOutputDeclaration(_xPOutputDeclaration_);
        setPOutputDeclaration(_pOutputDeclaration_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPOutputDeclaration getXPOutputDeclaration()
    {
        return _xPOutputDeclaration_;
    }

    public void setXPOutputDeclaration(XPOutputDeclaration node)
    {
        if (_xPOutputDeclaration_ != null)
        {
            _xPOutputDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPOutputDeclaration_ = node;
    }

    public POutputDeclaration getPOutputDeclaration()
    {
        return _pOutputDeclaration_;
    }

    public void setPOutputDeclaration(POutputDeclaration node)
    {
        if (_pOutputDeclaration_ != null)
        {
            _pOutputDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pOutputDeclaration_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPOutputDeclaration_ == child)
        {
            _xPOutputDeclaration_ = null;
        }

        if (_pOutputDeclaration_ == child)
        {
            _pOutputDeclaration_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPOutputDeclaration_) +
            toString(_pOutputDeclaration_);
    }
}
