/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PPriorityProd extends XPPriorityProd
{
    private XPPriorityProd _xPPriorityProd_;
    private PPriorityProd _pPriorityProd_;

    public X1PPriorityProd()
    {
    }

    public X1PPriorityProd(
        XPPriorityProd _xPPriorityProd_,
        PPriorityProd _pPriorityProd_)
    {
        setXPPriorityProd(_xPPriorityProd_);
        setPPriorityProd(_pPriorityProd_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPPriorityProd getXPPriorityProd()
    {
        return _xPPriorityProd_;
    }

    public void setXPPriorityProd(XPPriorityProd node)
    {
        if (_xPPriorityProd_ != null)
        {
            _xPPriorityProd_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPPriorityProd_ = node;
    }

    public PPriorityProd getPPriorityProd()
    {
        return _pPriorityProd_;
    }

    public void setPPriorityProd(PPriorityProd node)
    {
        if (_pPriorityProd_ != null)
        {
            _pPriorityProd_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pPriorityProd_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPPriorityProd_ == child)
        {
            _xPPriorityProd_ = null;
        }

        if (_pPriorityProd_ == child)
        {
            _pPriorityProd_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPPriorityProd_) +
            toString(_pPriorityProd_);
    }
}
