/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PStatePort extends XPStatePort
{
    private XPStatePort _xPStatePort_;
    private PStatePort _pStatePort_;

    public X1PStatePort()
    {
    }

    public X1PStatePort(
        XPStatePort _xPStatePort_,
        PStatePort _pStatePort_)
    {
        setXPStatePort(_xPStatePort_);
        setPStatePort(_pStatePort_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPStatePort getXPStatePort()
    {
        return _xPStatePort_;
    }

    public void setXPStatePort(XPStatePort node)
    {
        if (_xPStatePort_ != null)
        {
            _xPStatePort_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPStatePort_ = node;
    }

    public PStatePort getPStatePort()
    {
        return _pStatePort_;
    }

    public void setPStatePort(PStatePort node)
    {
        if (_pStatePort_ != null)
        {
            _pStatePort_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pStatePort_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPStatePort_ == child)
        {
            _xPStatePort_ = null;
        }

        if (_pStatePort_ == child)
        {
            _pStatePort_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPStatePort_) +
            toString(_pStatePort_);
    }
}
