/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PTaskInvocation extends XPTaskInvocation
{
    private XPTaskInvocation _xPTaskInvocation_;
    private PTaskInvocation _pTaskInvocation_;

    public X1PTaskInvocation()
    {
    }

    public X1PTaskInvocation(
        XPTaskInvocation _xPTaskInvocation_,
        PTaskInvocation _pTaskInvocation_)
    {
        setXPTaskInvocation(_xPTaskInvocation_);
        setPTaskInvocation(_pTaskInvocation_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPTaskInvocation getXPTaskInvocation()
    {
        return _xPTaskInvocation_;
    }

    public void setXPTaskInvocation(XPTaskInvocation node)
    {
        if (_xPTaskInvocation_ != null)
        {
            _xPTaskInvocation_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPTaskInvocation_ = node;
    }

    public PTaskInvocation getPTaskInvocation()
    {
        return _pTaskInvocation_;
    }

    public void setPTaskInvocation(PTaskInvocation node)
    {
        if (_pTaskInvocation_ != null)
        {
            _pTaskInvocation_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTaskInvocation_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPTaskInvocation_ == child)
        {
            _xPTaskInvocation_ = null;
        }

        if (_pTaskInvocation_ == child)
        {
            _pTaskInvocation_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPTaskInvocation_) +
            toString(_pTaskInvocation_);
    }
}
