/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X1PTimeslot extends XPTimeslot
{
    private XPTimeslot _xPTimeslot_;
    private PTimeslot _pTimeslot_;

    public X1PTimeslot()
    {
    }

    public X1PTimeslot(
        XPTimeslot _xPTimeslot_,
        PTimeslot _pTimeslot_)
    {
        setXPTimeslot(_xPTimeslot_);
        setPTimeslot(_pTimeslot_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPTimeslot getXPTimeslot()
    {
        return _xPTimeslot_;
    }

    public void setXPTimeslot(XPTimeslot node)
    {
        if (_xPTimeslot_ != null)
        {
            _xPTimeslot_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPTimeslot_ = node;
    }

    public PTimeslot getPTimeslot()
    {
        return _pTimeslot_;
    }

    public void setPTimeslot(PTimeslot node)
    {
        if (_pTimeslot_ != null)
        {
            _pTimeslot_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTimeslot_ = node;
    }

    void removeChild(Node child)
    {
        if (_xPTimeslot_ == child)
        {
            _xPTimeslot_ = null;
        }

        if (_pTimeslot_ == child)
        {
            _pTimeslot_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPTimeslot_) +
            toString(_pTimeslot_);
    }
}
