/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PActualGlobalParameter extends XPActualGlobalParameter
{
    private PActualGlobalParameter _pActualGlobalParameter_;

    public X2PActualGlobalParameter()
    {
    }

    public X2PActualGlobalParameter(
        PActualGlobalParameter _pActualGlobalParameter_)
    {
        setPActualGlobalParameter(_pActualGlobalParameter_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PActualGlobalParameter getPActualGlobalParameter()
    {
        return _pActualGlobalParameter_;
    }

    public void setPActualGlobalParameter(PActualGlobalParameter node)
    {
        if (_pActualGlobalParameter_ != null)
        {
            _pActualGlobalParameter_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pActualGlobalParameter_ = node;
    }

    void removeChild(Node child)
    {
        if (_pActualGlobalParameter_ == child)
        {
            _pActualGlobalParameter_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pActualGlobalParameter_);
    }
}
