/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PActualScopedParameterTail extends XPActualScopedParameterTail
{
    private PActualScopedParameterTail _pActualScopedParameterTail_;

    public X2PActualScopedParameterTail()
    {
    }

    public X2PActualScopedParameterTail(
        PActualScopedParameterTail _pActualScopedParameterTail_)
    {
        setPActualScopedParameterTail(_pActualScopedParameterTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PActualScopedParameterTail getPActualScopedParameterTail()
    {
        return _pActualScopedParameterTail_;
    }

    public void setPActualScopedParameterTail(PActualScopedParameterTail node)
    {
        if (_pActualScopedParameterTail_ != null)
        {
            _pActualScopedParameterTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pActualScopedParameterTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pActualScopedParameterTail_ == child)
        {
            _pActualScopedParameterTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pActualScopedParameterTail_);
    }
}
