/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PActualGlobalParameterTail extends XPActualGlobalParameterTail
{
    private PActualGlobalParameterTail _pActualGlobalParameterTail_;

    public X2PActualGlobalParameterTail()
    {
    }

    public X2PActualGlobalParameterTail(
        PActualGlobalParameterTail _pActualGlobalParameterTail_)
    {
        setPActualGlobalParameterTail(_pActualGlobalParameterTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PActualGlobalParameterTail getPActualGlobalParameterTail()
    {
        return _pActualGlobalParameterTail_;
    }

    public void setPActualGlobalParameterTail(PActualGlobalParameterTail node)
    {
        if (_pActualGlobalParameterTail_ != null)
        {
            _pActualGlobalParameterTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pActualGlobalParameterTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pActualGlobalParameterTail_ == child)
        {
            _pActualGlobalParameterTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pActualGlobalParameterTail_);
    }
}
