/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PActualPort extends XPActualPort
{
    private PActualPort _pActualPort_;

    public X2PActualPort()
    {
    }

    public X2PActualPort(
        PActualPort _pActualPort_)
    {
        setPActualPort(_pActualPort_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PActualPort getPActualPort()
    {
        return _pActualPort_;
    }

    public void setPActualPort(PActualPort node)
    {
        if (_pActualPort_ != null)
        {
            _pActualPort_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pActualPort_ = node;
    }

    void removeChild(Node child)
    {
        if (_pActualPort_ == child)
        {
            _pActualPort_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pActualPort_);
    }
}
