/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PFormalPortTail extends XPFormalPortTail
{
    private PFormalPortTail _pFormalPortTail_;

    public X2PFormalPortTail()
    {
    }

    public X2PFormalPortTail(
        PFormalPortTail _pFormalPortTail_)
    {
        setPFormalPortTail(_pFormalPortTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PFormalPortTail getPFormalPortTail()
    {
        return _pFormalPortTail_;
    }

    public void setPFormalPortTail(PFormalPortTail node)
    {
        if (_pFormalPortTail_ != null)
        {
            _pFormalPortTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFormalPortTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pFormalPortTail_ == child)
        {
            _pFormalPortTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pFormalPortTail_);
    }
}
