/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PHardwareDeclarationTail extends XPHardwareDeclarationTail
{
    private PHardwareDeclarationTail _pHardwareDeclarationTail_;

    public X2PHardwareDeclarationTail()
    {
    }

    public X2PHardwareDeclarationTail(
        PHardwareDeclarationTail _pHardwareDeclarationTail_)
    {
        setPHardwareDeclarationTail(_pHardwareDeclarationTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PHardwareDeclarationTail getPHardwareDeclarationTail()
    {
        return _pHardwareDeclarationTail_;
    }

    public void setPHardwareDeclarationTail(PHardwareDeclarationTail node)
    {
        if (_pHardwareDeclarationTail_ != null)
        {
            _pHardwareDeclarationTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pHardwareDeclarationTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pHardwareDeclarationTail_ == child)
        {
            _pHardwareDeclarationTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pHardwareDeclarationTail_);
    }
}
