/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PModuleDeclarationTail extends XPModuleDeclarationTail
{
    private PModuleDeclarationTail _pModuleDeclarationTail_;

    public X2PModuleDeclarationTail()
    {
    }

    public X2PModuleDeclarationTail(
        PModuleDeclarationTail _pModuleDeclarationTail_)
    {
        setPModuleDeclarationTail(_pModuleDeclarationTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PModuleDeclarationTail getPModuleDeclarationTail()
    {
        return _pModuleDeclarationTail_;
    }

    public void setPModuleDeclarationTail(PModuleDeclarationTail node)
    {
        if (_pModuleDeclarationTail_ != null)
        {
            _pModuleDeclarationTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pModuleDeclarationTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pModuleDeclarationTail_ == child)
        {
            _pModuleDeclarationTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pModuleDeclarationTail_);
    }
}
