/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PNetworkTimeslotDeclarationTail extends XPNetworkTimeslotDeclarationTail
{
    private PNetworkTimeslotDeclarationTail _pNetworkTimeslotDeclarationTail_;

    public X2PNetworkTimeslotDeclarationTail()
    {
    }

    public X2PNetworkTimeslotDeclarationTail(
        PNetworkTimeslotDeclarationTail _pNetworkTimeslotDeclarationTail_)
    {
        setPNetworkTimeslotDeclarationTail(_pNetworkTimeslotDeclarationTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNetworkTimeslotDeclarationTail getPNetworkTimeslotDeclarationTail()
    {
        return _pNetworkTimeslotDeclarationTail_;
    }

    public void setPNetworkTimeslotDeclarationTail(PNetworkTimeslotDeclarationTail node)
    {
        if (_pNetworkTimeslotDeclarationTail_ != null)
        {
            _pNetworkTimeslotDeclarationTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNetworkTimeslotDeclarationTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pNetworkTimeslotDeclarationTail_ == child)
        {
            _pNetworkTimeslotDeclarationTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNetworkTimeslotDeclarationTail_);
    }
}
