/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PNetworkTimeslotDeclaration extends XPNetworkTimeslotDeclaration
{
    private PNetworkTimeslotDeclaration _pNetworkTimeslotDeclaration_;

    public X2PNetworkTimeslotDeclaration()
    {
    }

    public X2PNetworkTimeslotDeclaration(
        PNetworkTimeslotDeclaration _pNetworkTimeslotDeclaration_)
    {
        setPNetworkTimeslotDeclaration(_pNetworkTimeslotDeclaration_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PNetworkTimeslotDeclaration getPNetworkTimeslotDeclaration()
    {
        return _pNetworkTimeslotDeclaration_;
    }

    public void setPNetworkTimeslotDeclaration(PNetworkTimeslotDeclaration node)
    {
        if (_pNetworkTimeslotDeclaration_ != null)
        {
            _pNetworkTimeslotDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pNetworkTimeslotDeclaration_ = node;
    }

    void removeChild(Node child)
    {
        if (_pNetworkTimeslotDeclaration_ == child)
        {
            _pNetworkTimeslotDeclaration_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pNetworkTimeslotDeclaration_);
    }
}
