/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PQualidentTail extends XPQualidentTail
{
    private PQualidentTail _pQualidentTail_;

    public X2PQualidentTail()
    {
    }

    public X2PQualidentTail(
        PQualidentTail _pQualidentTail_)
    {
        setPQualidentTail(_pQualidentTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PQualidentTail getPQualidentTail()
    {
        return _pQualidentTail_;
    }

    public void setPQualidentTail(PQualidentTail node)
    {
        if (_pQualidentTail_ != null)
        {
            _pQualidentTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pQualidentTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pQualidentTail_ == child)
        {
            _pQualidentTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pQualidentTail_);
    }
}
