/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PScheduleConnectionTail extends XPScheduleConnectionTail
{
    private PScheduleConnectionTail _pScheduleConnectionTail_;

    public X2PScheduleConnectionTail()
    {
    }

    public X2PScheduleConnectionTail(
        PScheduleConnectionTail _pScheduleConnectionTail_)
    {
        setPScheduleConnectionTail(_pScheduleConnectionTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PScheduleConnectionTail getPScheduleConnectionTail()
    {
        return _pScheduleConnectionTail_;
    }

    public void setPScheduleConnectionTail(PScheduleConnectionTail node)
    {
        if (_pScheduleConnectionTail_ != null)
        {
            _pScheduleConnectionTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pScheduleConnectionTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pScheduleConnectionTail_ == child)
        {
            _pScheduleConnectionTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pScheduleConnectionTail_);
    }
}
