/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PSensorDeclaration extends XPSensorDeclaration
{
    private PSensorDeclaration _pSensorDeclaration_;

    public X2PSensorDeclaration()
    {
    }

    public X2PSensorDeclaration(
        PSensorDeclaration _pSensorDeclaration_)
    {
        setPSensorDeclaration(_pSensorDeclaration_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PSensorDeclaration getPSensorDeclaration()
    {
        return _pSensorDeclaration_;
    }

    public void setPSensorDeclaration(PSensorDeclaration node)
    {
        if (_pSensorDeclaration_ != null)
        {
            _pSensorDeclaration_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pSensorDeclaration_ = node;
    }

    void removeChild(Node child)
    {
        if (_pSensorDeclaration_ == child)
        {
            _pSensorDeclaration_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pSensorDeclaration_);
    }
}
