/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PTimeslot extends XPTimeslot
{
    private PTimeslot _pTimeslot_;

    public X2PTimeslot()
    {
    }

    public X2PTimeslot(
        PTimeslot _pTimeslot_)
    {
        setPTimeslot(_pTimeslot_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PTimeslot getPTimeslot()
    {
        return _pTimeslot_;
    }

    public void setPTimeslot(PTimeslot node)
    {
        if (_pTimeslot_ != null)
        {
            _pTimeslot_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTimeslot_ = node;
    }

    void removeChild(Node child)
    {
        if (_pTimeslot_ == child)
        {
            _pTimeslot_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pTimeslot_);
    }
}
