/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2PTimeslotDeclarationTail extends XPTimeslotDeclarationTail
{
    private PTimeslotDeclarationTail _pTimeslotDeclarationTail_;

    public X2PTimeslotDeclarationTail()
    {
    }

    public X2PTimeslotDeclarationTail(
        PTimeslotDeclarationTail _pTimeslotDeclarationTail_)
    {
        setPTimeslotDeclarationTail(_pTimeslotDeclarationTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PTimeslotDeclarationTail getPTimeslotDeclarationTail()
    {
        return _pTimeslotDeclarationTail_;
    }

    public void setPTimeslotDeclarationTail(PTimeslotDeclarationTail node)
    {
        if (_pTimeslotDeclarationTail_ != null)
        {
            _pTimeslotDeclarationTail_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTimeslotDeclarationTail_ = node;
    }

    void removeChild(Node child)
    {
        if (_pTimeslotDeclarationTail_ == child)
        {
            _pTimeslotDeclarationTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pTimeslotDeclarationTail_);
    }
}
