/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.node;


public final class X2TIdent extends XTIdent
{
    private TIdent _tIdent_;

    public X2TIdent()
    {
    }

    public X2TIdent(
        TIdent _tIdent_)
    {
        setTIdent(_tIdent_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public TIdent getTIdent()
    {
        return _tIdent_;
    }

    public void setTIdent(TIdent node)
    {
        if (_tIdent_ != null)
        {
            _tIdent_.parent(null);
        }

        if (node != null)
        {
            if (node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tIdent_ = node;
    }

    void removeChild(Node child)
    {
        if (_tIdent_ == child)
        {
            _tIdent_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_tIdent_);
    }
}
