/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#include "h_table.h"

void host_init_HeliControl () {
#ifdef DISTRIBUTED
  init_HeliControl ();
#endif
}

void host_init_HeliNavigation () {
#ifdef DISTRIBUTED
  init_HeliNavigation ();
#endif
}

void host_init_HeliEmpty () {
#ifdef DISTRIBUTED
  init_HeliEmpty ();
#endif
}

host_type host_table[MAXHOST];
