/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.lexer;

/**
 * @author M.A.A. Sanvido
 * @version LexerException.java,v 1.4 2004/10/01 01:10:26 cxh Exp
 * @since Giotto 1.0.1
 */
public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
