/* This file was generated by SableCC (http://www.sablecc.org/). */

package giotto.giottoc.parser;

import giotto.giottoc.node.Token;

/**
 * @author M.A.A. Sanvido
 * @version ParserException.java,v 1.5 2004/10/01 01:10:29 cxh Exp
 * @since Giotto 1.0.1
 */
public class ParserException extends Exception
{
    Token token;

    public ParserException(Token token, String  message)
    {
        super(message);
        this.token = token;
    }

    public Token getToken()
    {
        return token;
    }
}
